/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    SmartMentorUPTA: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "estudiante",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "anio",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "trimestre",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "monto",
              type: "uint256",
            },
          ],
          name: "PagoRealizado",
          type: "event",
        },
        {
          inputs: [],
          name: "admin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "costoTrimestre",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_nuevoCosto",
              type: "uint256",
            },
          ],
          name: "establecerCosto",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_anio",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "_trimestre",
              type: "uint8",
            },
          ],
          name: "pagarTrimestre",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          name: "registroPagos",
          outputs: [
            {
              internalType: "bool",
              name: "pagado",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "monto",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "fecha",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
  },
  11155111: {
    SmartMentorUPTA: {
      address: "0x86e0CaaBF647DBAb3cCaA47725de6F0657Be6194",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "estudiante",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "anio",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "trimestre",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "monto",
              type: "uint256",
            },
          ],
          name: "PagoRealizado",
          type: "event",
        },
        {
          inputs: [],
          name: "admin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "costoTrimestre",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_nuevoCosto",
              type: "uint256",
            },
          ],
          name: "establecerCosto",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_anio",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "_trimestre",
              type: "uint8",
            },
          ],
          name: "pagarTrimestre",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          name: "registroPagos",
          outputs: [
            {
              internalType: "bool",
              name: "pagado",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "monto",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "fecha",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10148642,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
